in:
  type: file
  path_prefix: ./data/html/sample
  parser:
    type: scraping_parser
    schema:
      - name: name
        type: string
        xpath: //*[@id='contentMain']/article/div[1]/div[1]/h1/text()
        regexp: (.+?)/.+?/.+?/.+?/.+
      - name: rent
        type: string
        xpath: //span[contains(text(), '賃料')]/../following-sibling::td[1]//text()
        regexp: .+
      - name: shikikin
        type: string
        xpath: //span[contains(text(), '敷金')]/../following-sibling::td[1]/text()
        regexp: (.+?)/.+
      - name: reikin
        type: string
        xpath: //span[contains(text(), '礼金')]/../following-sibling::td[1]/text()
        regexp: (.+?)/.+
      - name: appearance_image
        type: json
        xpath: //p[contains(text(), '外観')]/preceding-sibling::span[1]//img/@src
        regexp: .+
      - name: floor_plan_image
        type: json
        xpath: //p[contains(text(), '間取図')]/preceding-sibling::span[1]//img/@src
        regexp: .+
out:
  type: stdout
